### ISSUE TITLE
comprata la versione PRO, pero' non ho ricevuto il codice

### ISSUE THREAD

**Issue by AlexSass** [shmykelsa/AAAD#10]
Ciao, ho comprato la versione Pro, ma non ho ricevuto nessun codice.
La mia email e' maffeialessio@hotmail.com.

Fammi sapere,
Grazie
Ciao
Alessio

**Comment by shmykelsa** [comment]
Salve, non deve essere ricevuto nessun codice. Basta procedere con la transazione e poi premere "Ritorna al venditore" come specificato nell'avviso all'inizio della procedura.

**Comment by AlexSass** [comment]
Mi spiace, credo di aver cliccato 'esci' e non ho completato l'operazione, ma il pagamento su Paypal e' comunque partito... Mi aiuti a risolvere il problema, possibilmente senza effettuare un secondo pagamento? (non e' per i 3.5euro, ma una questione di principio). Fammi sapere, grazie, Alessio

**Comment by AlexSass** [comment]
Mi spiace, credo di aver cliccato 'esci' e non ho completato l'operazione, ma il pagamento su Paypal e' comunque partito... Mi aiuti a risolvere il problema, possibilmente senza effettuare un secondo pagamento? (non e' per i 3.5euro, ma una questione di principio). Fammi sapere, grazie, Alessio

________________________________

**Comment by shmykelsa** [comment]
Se il tuo stato di versione PRO non viene riconosciuto, ti prego di scrivere una mail a ***@***.******@***.***> seguendo le seguenti istruzioni:

- Apri AAAD
- Apri menu in alto a destra
- Seleziona "Info"
- Scorri in basso il testo fino in fondo se la finestra occupa tutto lo schermo
- Inviami lo screenshot via mail

Provvederò all’attivazione della versione PRO

Cordiali Saluti!
Gabriele Rizzo aka Shmykelsa


Da: ***@***.***>
Inviato: sabato 1 maggio 2021 20:22
A: ***@***.***>
Cc: Gabriele ***@***.***>; State ***@***.***>
Oggetto: Re: [shmykelsa/AAAD] comprata la versione PRO, pero' non ho ricevuto il codice (#10)

Mi spiace, credo di aver cliccato 'esci' e non ho completato l'operazione, ma il pagamento su Paypal e' comunque partito... Mi aiuti a risolvere il problema, possibilmente senza effettuare un secondo pagamento? (non e' per i 3.5euro, ma una questione di principio). Fammi sapere, grazie, Alessio

________________________________
