### ISSUE TITLE
no new news on this tour? this message 

### ISSUE THREAD

**Issue by djmalin** [shmykelsa/AAAD#109]
Hello everyone, I have a phone xiaomi lite 11 4g and android 11 (no root), application version aa 6.6.112203 release daily, the screen2auto icon is available in aam when I click and s2a this message pops up (no new messages during this route) and I do not know if can someone help me with this, screen2 auto installs through the chrome browser and opens aaad installation.

**Comment by shmykelsa** [comment]
Refer to this issue: https://github.com/shmykelsa/AAAD/issues/101
