### ISSUE TITLE
Download non finalizzato ma conteggiato.

### ISSUE THREAD

**Issue by guanoapes77** [shmykelsa/AAAD#11]
Ciao, e complimenti! Ho installato AAAD la 1° versione, ho provato a scaricare CarStream ma il download non è iniziato, (solo spinning circle), nonostante ciò mi ha scalato il download... Ciao

**Comment by Theangel81** [comment]
Stessa cosa accaduta anche a me.....

**Comment by shmykelsa** [comment]
Salve, contattare help.aaad@gmail.com
