### ISSUE TITLE
Android Auto Update Required.

### ISSUE THREAD

**Issue by Kinglong84** [shmykelsa/AAAD#115]
hello, I'm Italian and I use google translated to write.  For two days it has been mandatory to update the Android auto app.  With the old version it does not start anymore.  If I update all AAAD apps they disappear.  how can i solve?  (PRO user)

**Comment by shmykelsa** [comment]
See #106 and #101

**Comment by Denusdv** [comment]
the same issue, struggling to find a workaround but seems like Google did their best preventing usage of any mirroring app with AA

**Comment by Kinglong84** [comment]
> hello, I'm Italian and I use google translated to write. For two days it has been mandatory to update the Android auto app. With the old version it does not start anymore. If I update all AAAD apps they disappear. how can i solve? (PRO user)



> See #106 and #101

thanks, I have solved installed "android auto" version 6.6.612544

**Comment by Denusdv** [comment]
hhm, seems like my problem is a bit different I do see all AAM apps but no matter what I try I get the same goddamn message
"NO NEW MESSAGES DURING THIS DRIVE"

I have

SASMSUM S8 galaxy 9.0.0 
"android auto" version 6.6.612544
Sreen2Auto 3.5.5
Hyundai Tucson 2021
