### ISSUE TITLE
AAAD Stuck in "loading" when trying to download an app.

### ISSUE THREAD

**Issue by IPushedU** [shmykelsa/AAAD#116]
My phone: Redmi Note 7 pro
Os version: 12.0.5.0
Android version: Android 10
Android auto version: 6.7.612934-release

AAAD downloaded and opened, all the required permissions and acces were given yet when trying to download farmata auto it gets stuck on the loading screen.
![Screenshot_2021-08-22-21-56-43-277_sksa aa customapps](https://user-images.githubusercontent.com/43817108/130368710-201f8623-61a4-49f1-9c73-4626572a80c4.jpg)

**Comment by Air88** [comment]
Same happend to me today

**Comment by LukeHussey** [comment]
I've got the same issue. It gets stuck "loading" indefinitely and ends up slowing down my phone to the point that locking and unlocking becomes a difficult feat. 

My phone: Samsung Galaxy S9
Android version: Android 10
Android auto version: 6.6.612534-release

**Comment by LukeHussey** [comment]
I've got the same issue. It gets stuck "loading" indefinitely and ends up slowing down my phone to the point that locking and unlocking becomes a difficult feat. 

My phone: Samsung Galaxy S9
Android version: Android 10
Android auto version: 6.6.612534-release

**Comment by licenciadosabrosito** [comment]
Same here, it appears this issue has also been raised on another thread but developer just doesn't care. Meh, I'll just delete the app and forget about it.

**Comment by shmykelsa** [comment]
Clear cache and datas of AAAD and try again

**Comment by ElHussler** [comment]
I've tried that but it doesn't work, it still just shows Loading until android tells me the app has stopped responding and shows wait/close.

**Comment by cuddylier** [comment]
Also seeing the same issue on a OnePlus, clearing cache and data doesn't help.

**Comment by Smoetzak** [comment]
Same here. Fresh install on a xiaomi mi 9t pro.
Also tried to delete data and cache. Even says AAAD isn't responding after a while being stuck on loading.

**Comment by CubanJew** [comment]
Try unplugging USB cable from AA head unit. That seems to fix it for me.

**Comment by HiramGRI** [comment]
I have the same problem and everything indicates why it is not because of the cell phone's gamma since there are cell phones with a very good gamma that the same thing happens to them.

**Comment by Harryevie** [comment]
No not resolved

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Oremuss** [comment]
Yup same here. Fresh install, custom ROM LineageOS 18.1, android 11. Its stuck loading while downloading.

**Comment by Harryevie** [comment]
Just had an android update and it's working again

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stockas** [comment]
The following worked for me:
1. Make sure you have the latest version of Android installed
2. Check that you allow AAAD to install unknown apps in the app settings. _(settings > apps > AAAD > scroll down to "install unknown apps" > make sure it is on "allowed"._
3. Restart your device

**Comment by ReconNinja117** [comment]
I'm having the same issue.  I tried everything in this thread, no luck.  I'm on a Galaxy S10e with Android 12, up to date.

**Comment by ElHussler** [comment]
I found that using a VPN with its location set to India lets me download normally

**Comment by fauzi-alfa-alfi** [comment]
![aaad](https://github.com/shmykelsa/AAAD/assets/114819628/4e0acd7a-12ff-4f3d-b15b-01191103cfe1)

I've got the same issue. "**AAAD isn't responding**" when download one of the apps.

My phone: Redmi Note 8 Pro
Android version: Android 11
Android auto version: 10.5.633834-release
