### ISSUE TITLE
Versione pro out

### ISSUE THREAD

**Issue by Ivanma81** [shmykelsa/AAAD#12]
Dopo aggiornamento a versione 1.2 non ho più la versione pro e mi scrive nessun download disponibile

**Comment by shmykelsa** [comment]
Unfortunately some technical difficulties are occurring with evaluating PRO version. 

If you are in this situation. Write a mail to help.aaad@gmail.com with subject "pro missing" and instructions will be sent. Thanks for the cooperation.
