### ISSUE TITLE
Realme issue

### ISSUE THREAD

**Issue by realme7** [shmykelsa/AAAD#124]
apps are showing but with error( no new message for this drive ), in all the apps such as fermata, carstream, aamirror , screan2auto etc. when it will fix? 
using realme 7 ,tried installing all the older versions of android auto ,,same issue in all the versions

**Comment by djste123** [comment]
Same problem with realme 8 pro updated to android 11.

I'm a AAAD pro user .

**Comment by Fernandoo6** [comment]
Just happen to me also 10/01/21. App not showing on Android auto at all
