### ISSUE TITLE
iGO NextGen 9.18.xxx via AA Mirror doesn't work

### ISSUE THREAD

**Issue by Tibor69** [shmykelsa/AAAD#128]
The AA Mirror works OK. I can see the apps on the car display and I can move these icons. 
But I launch Igo NextGen app the display show only black screen , but I can hear the voice navigation of the iGo app on the car's speakers. The iGO run on the unrooted Android 10 mobile.
My another old rooted Android 7.0 mobile this iGO NextGen app via AA Mirror works perfectly.

How can I repair this issue?

**Comment by shmykelsa** [comment]
I'm sorry but this issue is not related to AAAD @Tibor69
