### ISSUE TITLE
Does AAAD work with Android 12

### ISSUE THREAD

**Issue by cjcpeter** [shmykelsa/AAAD#134]
Does AAAD work with Android 12 on Pixel 4a device?

**Comment by luisgonzalezgonzalez** [comment]
on a pixel 4 no.. :-(

**Comment by shmykelsa** [comment]
I'll try to reproduce this on an emulator. Right now I don't have any Android 12-enabled device (and I'm away from keyboard due to a leave for medical reasons)

Thanks for the feedback

**Comment by cruxlin** [comment]
on pixel5 with Android 12: Yes

**Comment by shmykelsa** [comment]
I've tried to emulate AAAD on Pixel 4 and Pixel 5 (emulated) and found no issues. @cjcpeter @luisgonzalezgonzalez keep in mind that after an OTA update you should re-install the apps from AAAD. Please try to uninstall the affected apps and re-install them again from AAAD. 

I'll keep this issue open for the time being.

**Comment by luisgonzalezgonzalez** [comment]
i have uninstalled both apps (AAAD and widgets for android) and same
problem. When i open widget for android and i select "add wigdet", then a
menu apper for availables widget, i select one and suddenly the app close.
If i open widget for android again , no widget is selected.
is there any way to debug the problem?
best regards

**Comment by shmykelsa** [comment]
So, this is not a problem with AAAD @luisgonzalezgonzalez . As stated in the FAQs (https://github.com/shmykelsa/AAAD/#i-have-a-problem-with-an-app-installed-by-aaad-could-you-help-me-out) you should seek help with the app's developer. Sorry.

**Comment by cjcpeter** [comment]
Upgrade to 12 and reinstall the app with no problem.

**Comment by wuast94** [comment]
I'm on a oneplus 9 pro with android 12 and no app is showing app, installed them all but no luck. Can I give you more infos to help debugging this?

**Comment by shmykelsa** [comment]
> I'm on a oneplus 9 pro with android 12 and no app is showing app, installed them all but no luck. Can I give you more infos to help debugging this?

After phone's software update, it is mandatory to reinstall apps coming from AAAD

**Comment by wuast94** [comment]
> > I'm on a oneplus 9 pro with android 12 and no app is showing app, installed them all but no luck. Can I give you more infos to help debugging this?
> 
> After phone's software update, it is mandatory to reinstall apps coming from AAAD

i did, removed all apps and then reinstalled all apps

**Comment by shmykelsa** [comment]
> > > I'm on a oneplus 9 pro with android 12 and no app is showing app, installed them all but no luck. Can I give you more infos to help debugging this?
> > 
> > 
> > After phone's software update, it is mandatory to reinstall apps coming from AAAD
> 
> i did, removed all apps and then reinstalled all apps

Please proceed as follows: 

- Open settings
- Select apps
- Select any of the app installed via AAAD
- Scroll down to the very bottom and make a screenshot
- Attach it

**Comment by wuast94** [comment]
![Uploading Screenshot_2021-11-26-09-29-29-23_fc704e6b13c4fb26bf5e411f75da84f2.jpg…]()

**Comment by wuast94** [comment]
![Screenshot_2021-11-26-09-29-29-23_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/16965460/143550607-0a178f42-5754-41dd-89cb-b43f9ca8187a.jpg)

**Comment by Rider143** [comment]
@shmykelsa I'm using Realme X2 pro with Custom Rom, shows no msg's during drive. It works in k20 pro. Can you please help me out.
