### ISSUE TITLE
Can't install sceen2auto

### ISSUE THREAD

**Issue by pdario** [shmykelsa/AAAD#137]
When I try to install sceen2auto, I go to the app site, select the latest version (3.6.1 now) and select to open it with AAAD. Then the phone says there's a problem with the package analysis.

What should I do?

**Comment by sFaxsy** [comment]
Same issue

**Comment by cgmojoco** [comment]
Same, parsing error when opening screen2auto via aaad

**Comment by cgmojoco** [comment]
I tried:
Uninstall AAD.
Clear data/cache  AA  7.0.614134-release
 Installing AA 6.3.611344
Install AAD.
Upon opening AA 6.3.611344 I am asked to ugrade AA or it will not run.
Have not been successful in getting AAD to show up in AA.

**Comment by AleJaviSalva** [comment]
Same issue

**Comment by shmykelsa** [comment]
Duplicate of #107 

Thanks for the feedbacks. I'm looking into it.

**Comment by pdario** [comment]
I see #107 is marked has closed, but I still can't install screen2auto.

Can you fix this?
