### ISSUE TITLE
google block patching

### ISSUE THREAD

**Issue by ahhl** [shmykelsa/AAAD#140]
roll back Android Auto dosent work anymore.
patched app just appear for short while, the disappear. i roll back to AA ver 6.9 which work for many months before.😭

**Comment by podimonanil** [comment]
Same for me too.
Rolled back to 7.0 , Fermata was back, but when I reconnected second time, it was gone.
Rolled back to 6.9, Fermata was back again, but when I reconnected a second time, it was gone 
Please someone find a walkaround.

**Comment by ahhl** [comment]
but when install S2A, it still work. so i think it just affect certain apk.

**Comment by stivado** [comment]
Today I managed to show Fermata auto in AA and open IPTV program but next time I started AA I can't see Fermata in AA.  I hope you smart people find a solution. 

I had to downgrade AA and then it worked as i said, only for one time, can't believe it.

**Comment by shmykelsa** [comment]
Fixed with Fermata Auto's update 1.8.8

Please update Fermata Auto through AAAD.
