### ISSUE TITLE
Versione pro persa

### ISSUE THREAD

**Issue by filidam89** [shmykelsa/AAAD#15]
Dopo aggiornamento a ver 1.2 non è più visto lo sblocco pro

**Comment by shmykelsa** [comment]
Unfortunately some technical difficulties are occurring with evaluating PRO version. 

If you are in this situation. Write a mail to help.aaad@gmail.com with subject "pro missing" and instructions will be sent. Thanks for the cooperation.

**Comment by shmykelsa** [comment]
Unfortunately some technical difficulties are occurring with evaluating PRO version. 

If you are in this situation. Write a mail to help.aaad@gmail.com with subject "pro missing" and instructions will be sent. Thanks for the cooperation.
