### ISSUE TITLE
Awaiting Realme, Oppo Support

### ISSUE THREAD

**Issue by Rider143** [shmykelsa/AAAD#150]
Thank you for your efforts and releasing updates, glad to hear work is on going in realme devices. Can't wait for the results.

**Comment by Rider143** [comment]
Any beta updates for this devices?

**Comment by RMMA1979** [comment]
Amigos y se a avanzado algo con realme ???? Saludos cordiales

**Comment by Rider143** [comment]
Awaiting for yhe updates on Realme devices... Regards

**Comment by RMMA1979** [comment]
Hay avances con realme o será mejor cambiar de celular tengo la aplicación pro y no puedo usarla

**Comment by Rider143** [comment]
> Hay avances con realme o será mejor cambiar de celular tengo la aplicación pro y no puedo usarla

The dev is working on a fix, can't wait for the release. If that works I'm ready to contribute for pro version.

**Comment by Taboexa** [comment]
Ya la hay

**Comment by yeray68** [comment]
Pues dime cómo , porque en mi realme sigue sin funcionar

**Comment by yeray68** [comment]
Sorry to say but these developers don't seem interested in making it work on OPPO or Realme

Siento decirlo, pero estos desarrolladores no parecen interesados en que funcione en OPPO ni en Realme

**Comment by shmykelsa** [comment]
Moved to #56
