### ISSUE TITLE
Fermata Auto App not working

### ISSUE THREAD

**Issue by rzkshah** [shmykelsa/AAAD#157]
When AA launches. Fermata Auto app is not available on the drawer. Even AA Mirror Plus is not working

**Comment by tmu5** [comment]
Same here. 
I have tried to uninstall fermata auto few times, but no difference.

I can see and open fermata auto 1.8.9. from phone, but in AA I  can't see app.

Don't know what to do next..

**Comment by adiralon10** [comment]
Same.

**Comment by tmu5** [comment]
Now it works again. I just installed Fermata Auto again hour ago. 

Just watching YouTube in my car again.

**Comment by adiralon10** [comment]
> Now it works again. I just installed Fermata Auto again hour ago.
> 
> Just watching YouTube in my car again.

Still not working for me.

**Comment by shmykelsa** [comment]
Check [current issues](https://github.com/shmykelsa/AAAD#current-issues)
