### ISSUE TITLE
AA Mirror

### ISSUE THREAD

**Issue by EmranHawwari** [shmykelsa/AAAD#158]
aa mirror has disappeared from Android Auto menu, needs a new update.

**Comment by topherMario** [comment]
Same here. Tried uninstall and reinstall several times. Downgraded Android auto updates and was able to get it to show up on the dashboard but it would not launch and then Android auto forced me to update.

**Comment by vin619** [comment]
same here AA Mirror disappeared after update

**Comment by shmykelsa** [comment]
Check [current issues](https://github.com/shmykelsa/AAAD#current-issues)
