### ISSUE TITLE
AA Mirror on Android Auto V7 Disappeared 

### ISSUE THREAD

**Issue by aymans123456** [shmykelsa/AAAD#159]
The following is my environment :
Mobile Samsung Galaxy A20
Android V11 B
Android Auto V7.1.614554
AAAD V1.4.3
AA Mirror V1.0

AA Mirror worked ONCE (with NO sound) then it disappeared completely from the Car Screen!!!
Can not get it to run again.

**Comment by vin619** [comment]
same here AA Mirror just disappeared after update

**Comment by WittWise** [comment]
Managed to find a temporary but very annoying fix,

1. Make sure your phone is unplugged from the car
2. Go to Settings>Apps>Android Auto>Storage>Clear Data
3. Now plug in your phone, (you'll have to go through Android auto setup again which means you'll have to put the car in park) and the apps should reappear

If your phone disconnects it may work for a little while if you plug it in again, but if you leave for longer than 30 min- an hour and come back, the apps will disappear again. VERY annoying but it works for now

**Comment by shmykelsa** [comment]
Check [current issues](https://github.com/shmykelsa/AAAD#current-issues)
