### ISSUE TITLE
Non riconosce la versione pro. 1.2

### ISSUE THREAD

**Issue by lucarenga84** [shmykelsa/AAAD#16]
Sono passato alla versione pro sulla 1.1  Tutto ok. Ho aggiornato alle 1.2 ma non mi riconosce più la pro.. cosa devo fare?

**Comment by shmykelsa** [comment]
Unfortunately some technical difficulties are occurring with evaluating PRO version. 

If you are in this situation. Write a mail to help.aaad@gmail.com with subject "pro missing" and instructions will be sent. Thanks for the cooperation.
