### ISSUE TITLE
How to stop enforced update to Android Auto on car startup?

### ISSUE THREAD

**Issue by aymans123456** [shmykelsa/AAAD#160]
AA Mirror is not working with me, so I tried to downgrade AA to V6.6 (as suggested) and disabled the auto update.
However, every time I connect my cable to the car, AA enforce and update to AA and still AA Mirror NOT WORKING.

How to stop enforced update to Android Auto on car startup?

**Comment by shmykelsa** [comment]
Check [current issues](https://github.com/shmykelsa/AAAD#current-issues)
