### ISSUE TITLE
All apps crashing on Android Auto (Fermata, Mirror Plus...) Android 12 S21 Ultra

### ISSUE THREAD

**Issue by realrodri** [shmykelsa/AAAD#166]
All apps are crashing on the newest S21 Ultra using latest Android Auto version. When I try to downgrade Android Auto, it forces me to update anyways. 

Any idea? Paid for PRO version.

**Comment by tanvincent87** [comment]
I have the exact same problem with S21 Ultra on Android 1 we, nothing works. the icons appear on my car screen but it crashes whenever I click it.

**Comment by zkllbc** [comment]
> All apps are crashing on the newest S21 Ultra using latest Android Auto version. When I try to downgrade Android Auto, it forces me to update anyways.
> 
> Any idea? Paid for PRO version.

Hi, same problem here all apps are crashing, I'm using S21.

**Comment by realrodri** [comment]
> .

This exact things! I paid for the PRO version  to see if any app worked, and nothing.

**Comment by shmykelsa** [comment]
Check [FAQs](https://github.com/shmykelsa/AAAD#why-the-heck-do-i-need-this-app-cant-i-just-install-the-apps-by-myslef)

**Comment by realrodri** [comment]
> Check [FAQs](https://github.com/shmykelsa/AAAD#why-the-heck-do-i-need-this-app-cant-i-just-install-the-apps-by-myslef)

Ok. How can I refund the PRO version and remove the license from my device?
