### ISSUE TITLE
Netflix Video showing black screen

### ISSUE THREAD

**Issue by AmithRajpal** [shmykelsa/AAAD#167]
Good day. 

Please would someone be able to help me by telling me how to fix the black screen issue that prevents me from watching a video on Netflix using Screen2Auto. 

I have tried downgrading android auto to version 6.3.6 but it does not install. 

Thank you in advance.

**Comment by shmykelsa** [comment]
Check [FAQs](https://github.com/shmykelsa/AAAD#why-the-heck-do-i-need-this-app-cant-i-just-install-the-apps-by-myslef)

**Comment by AmithRajpal** [comment]
Why was my question closed by Shmykelsa. If you do not have an answer, then please stay out of it. This was a request for any members that may have experienced the same issue. 

Pointing me to FAQ's that do not answer my question is of no help to anyone. Thanks.

**Comment by albenex** [comment]
> Why was my question closed by Shmykelsa. If you do not have an answer, then please stay out of it. This was a request for any members that may have experienced the same issue.
> 
> Pointing me to FAQ's that do not answer my question is of no help to anyone. Thanks.

you’re posting into AAAD. its task is to install and show 3rd party’s AA apps into car. 

your issue has to be investigated on Screen2Auto section, probably

**Comment by AmithRajpal** [comment]
Thank you.  I will pay on those forum. Forgive my ignorance I'm me too
github and reddit.
