### ISSUE TITLE
Screen2Auto no touchscreen input from head unit. 

### ISSUE THREAD

**Issue by MRFU510N88** [shmykelsa/AAAD#168]
No mirroring apps seem to function correctly from AAAD.

The mirror appears on the head unit, however no touch input on mirrored screen or widget. 

Touch input only works on handset.

Any help with this would be greatly appreciated, I have seen many others with this issue also. 

Samsung Galaxy S21.
Android 12.
Android Auto v7.1.624574 release.
Screen2auto v3.6.2

**Comment by shmykelsa** [comment]
Check [FAQs](https://github.com/shmykelsa/AAAD#why-the-heck-do-i-need-this-app-cant-i-just-install-the-apps-by-myslef)
