### ISSUE TITLE
Ho perso la versione pro scaricando la 1.2

### ISSUE THREAD

**Issue by lucadigiulio** [shmykelsa/AAAD#17]
Dopo aver installato l'ultima versione, non risulto più avere la versione pro e mi dice un download a disposizione

**Comment by shmykelsa** [comment]
Unfortunately some technical difficulties are occurring with evaluating PRO version. 

If you are in this situation. Write a mail to help.aaad@gmail.com with subject "pro missing" and instructions will be sent. Thanks for the cooperation.
