### ISSUE TITLE
AAAD installs fermata, but fermata is not being displayed in Android Auto interface

### ISSUE THREAD

**Issue by Brunorvd** [shmykelsa/AAAD#177]
Hi, I just installed fermata auto using AAAD, it installs Ok (including fermata control) but just fermata control is being displayed in Android Auto interface.
I'm using Android 11 (Lineage OS 18.1).

**Comment by abhayathapa** [comment]
same issue for me

**Comment by brunoruanvd** [comment]
I'm back to stock rom because of this issue, tried some workaround, but nothing works

**Comment by yatbab** [comment]
Same problem with me - Android auto just showing Fermata Control and not Fermata Auto in Android auto

**Comment by w3irdo** [comment]
Same here. How can I download again?

**Comment by shmykelsa** [comment]
As you are running a custom ROM, it's much more preferred to use [AA AIO TWEAKER](https://github.com/shmykelsa/AA-Tweaker) instead.

**Comment by muppetofdoom** [comment]
Hi, anyone find an answer for this ? , same problem here, pixel 6 pro android 13 ?
