### ISSUE TITLE
After reinstal it is not responding and touch not works

### ISSUE THREAD

**Issue by marcopio97** [shmykelsa/AAAD#184]
The first instal aaad APK works perfectly. I delate it, my mistake, but after the second instal it not respond and the touch not works.
I have mi9t xiaomi.
Thks.

**Comment by marcopio97** [comment]
The version the 1.4.3

**Comment by shmykelsa** [comment]
AAAD allows one download per month. Uninstalling one of the downloaded apps won't give you the right to download again because the download actually happened.
