### ISSUE TITLE
is the payment safe? are we sure they don't steal paypal logins?

### ISSUE THREAD

**Issue by snato94-bis** [shmykelsa/AAAD#188]
is the payment safe? are we sure they don't steal paypal logins?

**Comment by nxtiak** [comment]
I just downloaded AAAD and my firs thought was this too! How do I know it's not a spoofed PayPal website that can steal our logins? This is a terrible implementation, no way for us to check the URL.

**Comment by nnhthuan** [comment]
Same here. I decided not to pay. Not safe for sure.

**Comment by shmykelsa** [comment]
Library used for payment can be seen here: https://github.com/KaustubhPatange/PayPal-IAP-for-Android/

Alternatively, [these instructions](https://github.com/KaustubhPatange/PayPal-IAP-for-Android/) are valid for pro version switch.

**Comment by nnhthuan** [comment]
That is unofficial paypal api, use it with your own risk then. I don't risk myself for this.
