### ISSUE TITLE
Versione Pro persa con l'ultimo aggiornamento 

### ISSUE THREAD

**Issue by Davidesilva89** [shmykelsa/AAAD#19]
Buona sera anche io ho perso la versione Pro dopo l'ultimo aggiornamento

**Comment by shmykelsa** [comment]
Unfortunately some technical difficulties are occurring with evaluating PRO version. 

If you are in this situation. Write a mail to help.aaad@gmail.com with subject "pro missing" and instructions will be sent. Thanks for the cooperation.
