### ISSUE TITLE
Mirror apps dont work with Samsung phones

### ISSUE THREAD

**Issue by cptapple** [shmykelsa/AAAD#194]
Hey, i've noticed that none of the mirroring apps work with Samsung phones. You can install it, it shows up in AndroidAuto, you can launch it but you either get a black screen or white screen.
- Tested on S9, S10, S20 with Android versions 9, 10, 11
- (all required) Permissions are granted 
- For mirroring i did press "start now" on prompt

Tried identical procedure on all other Android phones and they work flawlessly (Huawei, Xiaomi, Sony, Oneplus...).
This is a 100% Samsung specific issue.
Been like this for weeks.

**Comment by shmykelsa** [comment]
See [FAQs](https://github.com/shmykelsa/AAAD#i-have-a-problem-with-an-app-installed-by-aaad-could-you-help-me-out)

**Comment by nnhthuan** [comment]
None of them work for latest Android auto, and do not downgrade your android auto for this reason. Latest android auto contains many more important things than this.

**Comment by cptapple** [comment]
> None of them work for latest Android auto, and do not downgrade your android auto for this reason. Latest android auto contains many more important things than this.

And what are those "more important things"?

**Comment by nnhthuan** [comment]
- Security fixes
- Safety func fixes
- Stability
- Dark mode, car ui
- Do not disturb func

In case of you still want to downgrade your android auto to use this app, that is totally okay, just remind that the performance of old version is also poor and lead to less safety.

Not relating, but I also want to remind that do not use this while driving, only use it when resting in your car.

Thanks and take care.

**Comment by shmykelsa** [comment]
Just to be clear: downgrading Android Auto is not suggested at all, and it probably won't fix the issue.

**Comment by nnhthuan** [comment]
Not sure why, but I did try to downgrade and it works.
