### ISSUE TITLE
Impossible to navigate because of no touchscreen.

### ISSUE THREAD

**Issue by Marcel21673** [shmykelsa/AAAD#195]
My car (mazda mx30) does not have a touchscreen, only a multimedia knob like BMW'S have.
Because of that it's almost impossible to navigate to the screens/apps, like youtube..
Is it possible to do something about this

**Comment by fwon2638** [comment]
You won't be able to use any youtube related app. You may wish to buy a carplay box plus an air remote.

https://www.aliexpress.com/item/1005003984876505.html?spm=a2g0o.productlist.0.0.14aa2bdelWG4db&algo_pvid=0cf7a79f-8a28-482e-9eda-d6756115a1e3&aem_p4p_detail=202205221728083211267195125840057189609&algo_exp_id=0cf7a79f-8a28-482e-9eda-d6756115a1e3-4&pdp_ext_f=%7B%22sku_id%22%3A%2212000027642377087%22%7D&pdp_npi=2%40dis%21AUD%21%2134.55%21%21%21%21%21%400b0a555616532656883558683e46b7%2112000027642377087%21sea

**Comment by shmykelsa** [comment]
Closed. Please [see FAQs](https://github.com/shmykelsa/AAAD#i-have-a-problem-with-an-app-installed-by-aaad-could-you-help-me-out) for more information.
