### ISSUE TITLE
Which CarStream version I should download?

### ISSUE THREAD

**Issue by nnhthuan** [shmykelsa/AAAD#199]
- CarStream 2.0.5 by Paesani2006
- CarStream 2.0.4 by Kristakos
- CarStream 2.0.2 by Eskter

I'm using Samsung A51, Android 12.

**Comment by lyonhart** [comment]
None of them, Android 12  is blocking out all software like this, The new Android auto update also blocks all this. Been asking questions all week but on the main page it states Android 12 doesn't work with Aaad software

**Comment by nnhthuan** [comment]
I can confirm that nothing is working! So bad !

**Comment by ryansmall75** [comment]
I have Android 13 and it works just fine for me

**Comment by Ishprecher** [comment]
> I have Android 13 and it works just fine for me

Ok, then why dont you answer the question
