### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by Fabio1968** [shmykelsa/AAAD#203]
Hello,
it's been a long time since the performance monitor app stopped working. I have the impression that your project has been abandoned also because I do not see many answers to the questions that are asked of you.
Smartphone
xiaomi 11 5g lite
miui 13.0.6 android 12
Thank you

**Comment by shmykelsa** [comment]
Closed. Please [see FAQs](https://github.com/shmykelsa/AAAD#i-have-a-problem-with-an-app-installed-by-aaad-could-you-help-me-out) for more information.
