### ISSUE TITLE
carstream crashes if trying to select different playback speed 

### ISSUE THREAD

**Issue by munecito** [shmykelsa/AAAD#209]
Hello. 

I don't know if this is a AAAD issue or a carstream one, but when trying to change the playback speed or the quality the app crashes and the video restarts. 

It happens on carstream 2.0.5 and 2.0.4 I haven't tried on the old version. 

This is in a Samsung galaxy z flip 3 Android 13 one UI 4.1.1 Kernel version 5.4.147-qgki-24879461-abF711BXXS3CVIG #1 Mon Sep 26 12:45:11 KST 2022

**Comment by shmykelsa** [comment]
Closed. Please [see FAQs](https://github.com/shmykelsa/AAAD#i-have-a-problem-with-an-app-installed-by-aaad-could-you-help-me-out) for more information.
