### ISSUE TITLE
Could OsmAnd~ from f-droid be included as well?

### ISSUE THREAD

**Issue by mcepl** [shmykelsa/AAAD#210]
That’s basically it.

https://f-droid.org/en/packages/net.osmand.plus/

**Comment by shmykelsa** [comment]
Thanks for the suggestion.

Indeed, it's possible. I must make sure that they did not strip down Android Auto compatibility from that version first. Also, being licensed, authorization from OsmAnd is necessary.

**Comment by 360path** [comment]
OsmAnd~ still doesn't show as an available app on AAAD.

**Comment by shmykelsa** [comment]
> OsmAnd~ still doesn't show as an available app on AAAD.

As OsmAnd Is available through Play Store, AAAD is not necessary at all. Android Auto is Google Services based so no point in hosting Play Store applications.

**Comment by 360path** [comment]
OsmAnd~ is different from OsmAnd (Free) and OsmAnd+ though, and not available through the Play Store.
