### ISSUE TITLE
aa mirror not working in android auto 8.4.624324

### ISSUE THREAD

**Issue by rajesh90475** [shmykelsa/AAAD#212]
aa mirror not working in android auto 8.4.624324 how to solve

**Comment by Sertech12** [comment]
I have the same issue, any helps would be really appreciated.

**Comment by yhlizl** [comment]
Me too, please help this

**Comment by shmykelsa** [comment]
Not related to AAAD - See [FAQs](https://github.com/shmykelsa/AAAD#i-have-a-problem-with-an-app-installed-by-aaad-could-you-help-me-out)

**Comment by yhlizl** [comment]
@shmykelsa but almost all apps in AAAD, I can't use them in the new version of the Android Auto.
I have a license in AAAD.

**Comment by TinoSic** [comment]
Anche a me non funzionano nulla più

**Comment by shmykelsa** [comment]
> @shmykelsa but almost all apps in AAAD, I can't use them in the new version of the Android Auto. I have a license in AAAD.

You have to keep in mind that AAAD acts as an app store. Kinda like Google Play Store, but its duty is to host apps for Android Auto and make them available on it. Obviously if you find an app on the Play Store and that does not work as expected, you won't blame Google. The fact that you have a license for AAAD gives you the right to download undefinitely. 

Quoting the FAQs:

> Any software installed by my app is provided "as is" and I'm not responsible for any malfunctioning. If you are in this case, please seek help from the software's author instead.
