### ISSUE TITLE
AAAD: Oppo/Realme devices are not compatible

### ISSUE THREAD

**Issue by cocomeros** [shmykelsa/AAAD#214]
**Oppo/Realme devices are not compatible** - Testing is in progress for a fix
I've been reading this sentence for two years. Is there any hope that someone can fix the problem? Or are we to think that the project has failed?

**Comment by angelsinistanbul** [comment]
+++++

**Comment by Loko998383** [comment]
When compatible Realme ?

**Comment by xMrRose** [comment]
Seems like all of the magic is done by these lines:
![image](https://user-images.githubusercontent.com/81589003/221539591-f50fd2f9-7677-4c4e-85a6-a752f8ecacf1.png)

Does anyone knows why it could not work in Oppo/Realme devices?
Some docs/hacks sources, how the validation is performed there?

**Comment by shmykelsa** [comment]
Moved to #56 as duplicate
