### ISSUE TITLE
Performance Monitor, non vedo lancette o valori

### ISSUE THREAD

**Issue by AlexSass** [shmykelsa/AAAD#22]
Ciao, ho scaricato Performance Monitor ma non vedo valori, ne lancette nei vari quadranti. Qualche consiglio?
Grazie Mille,
Alex

**Comment by tommytech71** [comment]
hai il lettore obd in auto ????
io ho un altro problema non riesco a mettere i limiti di scala in questo software e quindi le lancette  sopratutto della pressione turbo non si alza

**Comment by AlexSass** [comment]
Ciao, non credo di avere un lettore OBD, ma è necessario?On 2 May 2021 14:21, tommytech71 ***@***.***> wrote:
hai il lettore obd in auto ????
io ho un altro problema non riesco a mettere i limiti di scala in questo software e quindi le lancette  sopratutto della pressione turbo non si alza

**Comment by marco97pa** [comment]
Il lettore OBD è un device fisico da acquistare ed è necessario per il corretto funzionamento. 
Detto questo, qui si possono aprire issues relativi all'app AAAD e al suo codice. La domanda riguarda Performance Monitor quindi è più corretto se chiedi ai loro sviluppatori. 

> Ciao, non credo di avere un lettore OBD, ma è necessario?On 2 May 2021 14:21, tommytech71 ***@***.***> wrote: hai il lettore obd in auto ???? io ho un altro problema non riesco a mettere i limiti di scala in questo software e quindi le lancette sopratutto della pressione turbo non si alza —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by shmykelsa** [comment]
Salve, per problemi riguardanti performance monitor, scrivere sul repo dedicato:

https://github.com/jilleb/mqb-pm/issues
