### ISSUE TITLE
Unable to find Fermata auto in Android 13, Realme 9pro

### ISSUE THREAD

**Issue by Tej1234567890** [shmykelsa/AAAD#220]
Please help as I couldn't find Fermata auto

Android Auto version: 8.5.624594
Android Version: 13
Fermata Control: 1.9
![Screenshot_2023-01-08-07-42-03-76_31f2d1fb8a9cb6537600cbf449362b94](https://user-images.githubusercontent.com/122137304/211178160-1c038664-6de3-4d70-a680-a20fda3a49b7.jpg)

**Comment by Medmimoza** [comment]
Go down to "version" clic several time on it, you will see developer mode enabled, then go to 3 dots on top and select developer setting : go down and enqble " unknown source.

**Comment by Medmimoza** [comment]
![Screenshot_20230108_222009_Android Auto](https://user-images.githubusercontent.com/66849332/211219786-315857af-f44a-466c-8d6b-1771bff7cf5f.jpg)

**Comment by TinoSic** [comment]
![Screenshot_2023-01-08-22-58-00-07_31f2d1fb8a9cb6537600cbf449362b94](https://user-images.githubusercontent.com/92671932/211221153-335ed047-db99-4209-827c-a7acc114ae65.jpg)
Attived but not working

**Comment by Medmimoza** [comment]
Close Android auto and oppen it again, this works only if you installed fermata from aaad

**Comment by TinoSic** [comment]
It doesn't work, I did all the possible tests... even rooting the smartphone, on some types it doesn't work for example one plus 5t, etc.

**Comment by Medmimoza** [comment]
You're right, just read phone type

**Comment by TinoSic** [comment]
???

**Comment by Medmimoza** [comment]
![Screenshot_20230108_232701_Chrome](https://user-images.githubusercontent.com/66849332/211222258-db59e5e8-e262-4995-9932-8b41c83bcc78.jpg)

**Comment by TinoSic** [comment]
Ok, thanks but I have one plus Nord 2t 5g

**Comment by Tej1234567890** [comment]
Thanks will wait for an update
