### ISSUE TITLE
Video sharing 

### ISSUE THREAD

**Issue by VankataStanchev** [shmykelsa/AAAD#226]
Hi guys , I have the AAAD mirror plus, buth I can play videos on the car screen (camaro 2018) 
The phone is connected to the car and waze is running fine but I can't share my phone screen on car screen to play You tube or some other video app.

**Comment by shmykelsa** [comment]
See [FAQs](https://github.com/shmykelsa/AAAD#i-have-a-problem-with-an-app-installed-by-aaad-could-you-help-me-out)
