### ISSUE TITLE
Error Connection 7

### ISSUE THREAD

**Issue by HenriqueCRodrigues** [shmykelsa/AAAD#230]
I installed this and click download inside app, after install crashing my Android auto with message reprovado security car, error connection 7, i can restore from last configure, before AAAD
![Screenshot_20230220_095124_Android Auto](https://user-images.githubusercontent.com/23089194/220181478-181aa16d-c28a-401d-8274-57dfaabafd6c.jpg)

**Comment by shmykelsa** [comment]
Unrelated to AAAD
