### ISSUE TITLE
Oppo workaround to use GoogleInstaller does not work

### ISSUE THREAD

**Issue by xMrRose** [shmykelsa/AAAD#233]
Workaround described in here:
https://github.com/shmykelsa/AAAD/wiki/Fix-for-OnePlus-Realme-Oppo
does not work for my Oppo.
Linked package installer is crashing.

Also I have noticed something.
Isn't the package installer [Instruction Package Installer](https://www.mediafire.com/file/vn1b3w2im7n4w52/com_android_packageinstaller_3_0_2369_150_minAPI29arm64_v8anodpi.apk/file) customized? I can see it differs from other one like [Google Package Installer](https://www.apkmirror.com/apk/google-inc/package-installer/package-installer-13-8768315-release/package-installer-13-8768315-android-apk-download/), using apktool decompiler.

Could you @shmykelsa give us some hints what have you done to make installer work? And what customization was performed?

**Comment by shmykelsa** [comment]
>  Workaround described in here:
> https://github.com/shmykelsa/AAAD/wiki/Fix-for-OnePlus-Realme-Oppo
> does not work for my Oppo.
> Linked package installer is crashing.

Are you sure you are tapping the right one? It's written to **do not tap** the one with the green stock Android icon. 

> Isn't the package installer [Instruction Package Installer](https://www.mediafire.com/file/vn1b3w2im7n4w52/com_android_packageinstaller_3_0_2369_150_minAPI29arm64_v8anodpi.apk/file) customized?

No, not modified

**Comment by xMrRose** [comment]
Hm now it worked...
So if it is not modified how come it is working?
I'd like to understand it. 
1) When I tap not the one with Android icon, isn't it like I have used the old one? Seems a bit confusing...
2) If the file is not modified could you please provide source? From where did you get it? (some apk mirror link or smth)

**Comment by shmykelsa** [comment]
> When I tap not the one with Android icon, isn't it like I have used the old one? Seems a bit confusing...

I know it's confusing, I honestly can't give a proper explanation to this either.

> If the file is not modified could you please provide source? From where did you get it? (some apk mirror link or smth, I'd like to know for the future updates and so on)

[Source](https://www.apkmirror.com/apk/oppo/package-installer-4/package-installer-4-3-0-2369-release/package-installer-3-0-2369-android-apk-download/)

**Comment by xMrRose** [comment]
Yeah, it's all work. Thanks man, you rock!
