### ISSUE TITLE
Loading infonito

### ISSUE THREAD

**Issue by TinoSic** [shmykelsa/AAAD#234]
Ciao perdona il disturbo, ma dopo aver fatto la procedura di fix per OnePlus  l'app per scaricare fermata 24 si blocca, rimane in loading durante lo scaricamento e poi crasha. ho provato a cancellare le cache dell' app ed anche a disinstallare l'app e reinstallarla.

**Comment by shmykelsa** [comment]
Please seek help through the app itself for a better support:

- Open top right menu
- Select "Help"
- Select yes 
- Compose an e-mail explaining the problem

**Comment by TinoSic** [comment]
In realtà non si è risolto nulla
