### ISSUE TITLE
Coolwalk Full Screen

### ISSUE THREAD

**Issue by shoxter** [shmykelsa/AAAD#238]
From everything I can tell, there isn't a way to disable the split screen, multi-card view that comes by default in Coolwalk 

This leaves all of the AAAD apps only able to use part of the screen for video.

I've tried disabling maps and the screen is still split but the once Maps card shows an error instead of maps.

Is there any workaround to this outside of downgrading? If I want to downgrade, what version of AA should I target?

Thanks!

**Comment by shmykelsa** [comment]
You can either force disable widescreen or force disable Coolwalk. I’m closing this issue for the moment as not related to AA AIO TWEAKER
