### ISSUE TITLE
Screen overlay apps

### ISSUE THREAD

**Issue by soNburst** [shmykelsa/AAAD#239]
Hello. I just purchased the pro version of aaad. I've been using this app for a while and it has been working great for years using Galaxy Note 20 ultra on different versions of android and Android auto up until the latest versions. I just upgraded to a Galaxy S23 Ultra with AA 6.9.x and although carstream and fermata auto are working, I can't seem to get AA Mirror or AA Mirror Plus to work. All permissions are given and when I allow for screen overlay, it just shows a black screen. Please let me know if there are any options I can play with in order to fix this issue. Thanks

**Comment by shmykelsa** [comment]
Unrelated to AAAD. Sort this out with AA Mirror and AA Mirror Plus’ developers
