### ISSUE TITLE
No New Messages Issue -- Car Stream | Pixel 6

### ISSUE THREAD

**Issue by JamieEC** [shmykelsa/AAAD#242]
Hi all,
Using Pixel 6 (No root), I have installed AAAD and installed Carstream. When I open carstream in the car I get the message 'No new messages during this drive' 

I have cleared cache for both Carstream and AA, restarted the phone, all the usual.

AAAD is now unresponsive, just Loading... at the bottom.

I have installed Fermata through other means and this works fine.

**Comment by Anatras02** [comment]
Same problem

**Comment by DragonSlayer88** [comment]
What other method did you use? I'm getting the same issue with any app I try to install.

**Comment by sircharlesxx** [comment]
I would like to know how fermata was installed in the alternative way that fixed this

**Comment by Jesse-Abruzzo** [comment]
Pixel 6 pro. Same issue. Using any method aaad or aastore, nothing works.

**Comment by jataiy** [comment]
Same issue, Pixel 6.

**Comment by austindetzel** [comment]
Have the same issue on a Pixel 7 Pro, tried reinstalling everything

**Comment by bronxnz** [comment]
Same issue with Pixel 6 and Carstream from AAAD or GitHub. Tried the alternative package installer, doesn't work. Tried the renaming and repackaging of Carstream, also doesn't work.

**Comment by justinfx** [comment]
Same problem on pixel 5. First installed with AAAD and got the message. Then tried to reinstalled with Kinginstaller but now it won't even register as an app in AA

**Comment by muppetofdoom** [comment]
Hi, any updates on this, same problem on Pixel 6 pro android 13?

**Comment by shmykelsa** [comment]
I'll move this fix to #247. Please check out the fix in the [wiki](https://github.com/shmykelsa/AAAD/wiki/Fix-for-Pixel-Android-13-)
