### ISSUE TITLE
Performance Monitor doesn´t open

### ISSUE THREAD

**Issue by tntrio** [shmykelsa/AAAD#25]
Hi, I´ve got the Issue that the performance monitor app does not open. After clicking on it closes directly.
I´ve seen that there are several issues mentioned regarding perfromance monitor but with help of the google-translator I´m not sure if this issue with closing app was mentioned before.

With an old rooted phone the performance monitor works on my Headunit and also delivers the correct values...

**Comment by stefy84** [comment]
Vorrei annullare l'iscrizione.

Il Lun 3 Mag 2021, 14:48 tntrio ***@***.***> ha scritto:

**Comment by tntrio** [comment]
Seems to be an issue from Performance Monitor App regarding MIUI, so issue can be closed
