### ISSUE TITLE
AA mirror plus not working on Samsung S23 ultra Android 13

### ISSUE THREAD

**Issue by akki23** [shmykelsa/AAAD#252]
Hi Team

As I tap on AA Mirror plus app on the car android auto. It shows black screen. The request doesn't show on mobile. If I open the same app on mobile accept for screen share request is seen. Once I accept, nothing happens and it is black screen on android auto display. I am using Samsung S23 Ultra with android version 13. Please help on this.

**Comment by shmykelsa** [comment]
See [notes](https://github.com/shmykelsa/AAAD#notes)
