### ISSUE TITLE
Torque pro

### ISSUE THREAD

**Issue by ilker-aktuna** [shmykelsa/AAAD#255]
Hi,

I want to use Torque pro on AA.
Is it possible with AAAD ?
If not, can you add it as an option ?

thanks.

**Comment by shmykelsa** [comment]
Performance Monitor is actually a Torque Pro plugin if you set it up correctly.

**Comment by ilker-aktuna** [comment]
Ok. How do we set it up ?
There is no mention of it on Torque pro

**Comment by shmykelsa** [comment]
Enable complete access under “plugin” settings on Torque Pro. Then set up the indicators to one of the values that have Torque pro icon on the right.


Il 26 giu 2023, 22:03 +0200, ilker Aktuna ***@***.***>, ha scritto:

**Comment by ilker-aktuna** [comment]
OK. Installed Performance Monitor from AAAD.

Enabled “complete access” on Torque pro plugins settings. But I don’t see “Performance Monitor” listed in “plugins”

After installing it , it also wanted to install VAG extensions for Android Auto.

But I don’t understand how I will access Torque views from here.

What am I doing wrong ?

**Comment by shmykelsa** [comment]
It is not meant to be listed. Just put the right dials on Performance Monitor.

**Comment by ilker-aktuna** [comment]
Ok thanks.

I have an issue;

When I change screens (go from Performance mon. to Google Maps and then back to Perf. Mon.), Pef. Mon. crashes.

And after that point it doesn’t come back until I start Torque Pro on my phone.

I guess, Perf. Mon. is looking for Torque Pro but it can not receive data for some reason.

Is there a solution for that ?

Some settings I missed ?

**Comment by shmykelsa** [comment]
It's better to move this conversation on the [appropriate repo](https://github.com/jilleb/mqb-pm)

**Comment by ilker-aktuna** [comment]
Unfortunately , that repo is archived and not open to discussions/issues.

 

This repository has been archived by the owner on Mar 11, 2022. It is now read-only.

**Comment by shmykelsa** [comment]
I'm sorry but I will have to close this issue as technically unrelated to AAAD
