### ISSUE TITLE
apps mirroring won't works

### ISSUE THREAD

**Issue by alipasto** [shmykelsa/AAAD#257]
Hallo to all,
First of all I wanna thanks to shmykelsa for the great work.
My problem is mirroring apps don't work well: I have oppo find x3 pro with colorOs 13.1.051 not rooted and when I launch aastream,  screen2auto or aamirror, and  I try to open an app, I can't see it on the infotainment screen but the app is open on the phone.

**Comment by shmykelsa** [comment]
See [notes](https://github.com/shmykelsa/AAAD#notes)
