### ISSUE TITLE
Violation of GPLv3

### ISSUE THREAD

**Issue by mhmtnasir** [shmykelsa/AAAD#258]
You used the https://github.com/blikoon/QRCodeScanner lib in your work. It is licensed by GPLv3.
The licensing agreement violates the GPLv3 (sublicensing is not allowed) (section 5), therefore it is invalid and I will be ignoring it.
Thank you.

**Comment by mhmtnasir** [comment]
Closed without any response, I see. I'll take that as a "did not take action" and continue with GPLv3 license on my fork.
Thank you.

**Comment by NotNoelChannel** [comment]
Reopen this if you dare @shmykelsa
