### ISSUE TITLE
Purchased Pro License - Upgraded My Device but AAAD Team will not help 

### ISSUE THREAD

**Issue by IngLogy77** [shmykelsa/AAAD#259]
Hello guys, I thought this was a great apk until I recently upgraded from my note 20 plus to the S23 Ultra, I forgot on how to transfer my license to my new device, so I wrote to AAAD Team and they told me to get my old device which I had already sold, so I bought back my old device to install the AAAD apk and now I still have not been able to reactivate the pro license, AAAD Team answered back that I should purchase again. What happens if some other client gets their device stolen and wants to install your apk I asked, their answer I received was that again I new license purchased should be made. I think this is complete nonsense, I own a lot of pro apks and this is the only one that has this ridiculous policy. So, am asking one more time for your help with my purchase.

**Comment by mhmtnasir** [comment]
Eh, just forget about it. Use KingInstaller and use [these files](https://github.com/mhmtnasir/AAAD/blob/main/local.properties) for the APKs.

**Comment by IngLogy77** [comment]
Got email from AAAD Team, let's see if we can get our license back.

**Comment by dutchboy347** [comment]
How did you get it restored? Emailed for help but nothing

**Comment by IngLogy77** [comment]
Hello, I wrote them a couple of times and left my review of app in the
playstore. Then they helped me out.
