### ISSUE TITLE
Recover License 

### ISSUE THREAD

**Issue by grymorum** [shmykelsa/AAAD#260]
Hello, I bought the PRO version, I reset the Android smartphone and I lost the license. I asked for help by email and they gave me some instructions that I don't understand, they ask me to send a screenshot, but even though I send a screenshot they tell me that it is not correct, could someone explain to me what I have to send?

**Comment by sircharlesxx** [comment]
cool. you should consider closing this issue then.

**Comment by grymorum** [comment]
Thanks
