### ISSUE TITLE
Where to find list of Android Auto apps?

### ISSUE THREAD

**Issue by jumpjack** [shmykelsa/AAAD#262]
Which are the Android Auto apps supported by this app?
And how do I retrieve from google the list of ALL apps compatible with Android Auto, to understand which ones were disabled by Google and re-enabled by the app?

Android Auto world is very confusing, I don't get why a simple "android auto" filter does not exist on play store.

**Comment by shmykelsa** [comment]
https://play.google.com/store/apps/editorial_collection/promotion_topic_3003388_androidauto_baselist?jsmode=du
