### ISSUE TITLE
Fermata is gone

### ISSUE THREAD

**Issue by lNSlD3R** [shmykelsa/AAAD#266]
fermata doesn't show anymore on android auto list of apps :(
It has been working just fine for over 18months, now its gone

I uninstalled reinstalled the AAAD, fermata. no results.

my phone is Oneplus 7t Pro

**Comment by shmykelsa** [comment]
See [known issues](https://github.com/shmykelsa/AAAD#-known-issues-)

**Comment by lNSlD3R** [comment]
Thank you
