### ISSUE TITLE
FreeTube integration

### ISSUE THREAD

**Issue by shadycloud** [shmykelsa/AAAD#268]
Can we get freetube working through here? https://github.com/MarmadileManteater/FreeTubeCordova

**Comment by shadycloud** [comment]
![Screenshot_20231022_171936_FreeTube Nightly](https://github.com/shmykelsa/AAAD/assets/13189052/62e95571-a12b-49f1-a6f3-4f8ca08159f1)

**Comment by shadycloud** [comment]
Actually,  I guess it could integrate the upstream repo, because the cordova link is the Android fork. 

https://github.com/FreeTubeApp/FreeTube

**Comment by shmykelsa** [comment]
See [FAQs](https://github.com/shmykelsa/AAAD#why-only-those-apps-where-is-youtube-where-is-netflix-where-is-instagram) for this.
