### ISSUE TITLE
Factory reset wiped my license

### ISSUE THREAD

**Issue by I-am-Gaming** [shmykelsa/AAAD#273]
I forgot to take a screenshot of license transfer QR code even though i paid it . It has been since 2 months . I even sent a mail but no response

**Comment by shmykelsa** [comment]
Please make sure you are following the instructions on [known issues section](https://github.com/shmykelsa/AAAD?tab=readme-ov-file#-known-issues-)

**Comment by I-am-Gaming** [comment]
I even download AAAD apk from GitHub not from any 3rd party
