### ISSUE TITLE
Donate dialog | ID is: 0000....

### ISSUE THREAD

**Issue by Co-TI** [shmykelsa/AAAD#276]
The app generally works. I would like to donate a beer to get the full functionality. 
But in donation dialog "Your ID is:" 00000000-0000-0000-0000-0000-000000000000-Jelly Star is displayed. 

I haven't donated yet, but I assume from the description that I have to get a unique ID beforehand and not consecutive zeros. 

-If the consecutive zeros are correct and I only receive a unique ID after donating, please indicate this in the donation dialog box.

-If the consecutive zeros are not correct, please indicate that I have received a unique ID in the store!

My Device is a Unihertz Jelly Star | Andoid 13

![APP](https://github.com/shmykelsa/AAAD/assets/155624804/c1f9271b-cbda-4542-89f5-005ef78109f0)

![STORE](https://github.com/shmykelsa/AAAD/assets/155624804/49eaaec6-0acd-4b79-aa9e-a71699110208)

**Comment by shmykelsa** [comment]
This is not AAAD.
