### ISSUE TITLE
Free 1 Download Used, but nothing Installed (bug)

### ISSUE THREAD

**Issue by melgcy** [shmykelsa/AAAD#277]
Good Day AAAD Team!

I hope this message finds you on good spirits!

I  would very much appreciate assistance regarding issue on the app that occured to me.

By the way, Im using a Samsung Galaxy A54 5G; Android Version 13

When I try to install fermata auto, it doesnt proceed, just keeps on loading until it stops responding, you are then given the option to 'wait' or 'close app'. 

I had assumed that my phone was just freezing to I begin to attempt then retry multiple times. Then later, on my 3rd "close app" It stopped saying not responding.  BUT It already consumed my free 1 download WITHOUT actually INSTALLING anything, and I have to wait 1month to get my first free download.

Can this be fixed? I tried clearing cache & data of the app then uninstall then reinstalled. Still consumed my free download. :c Im sad that I'll have to wait 1 month due to a bug. I hope you read this soon and maybe fix this bug and receive my 1 download! Thanks in advance! AAAD team c:

![Screenshot_20240107_091055_AAAD](https://github.com/shmykelsa/AAAD/assets/65751632/ea928e0b-0b13-4a2f-991a-4fc7a9997c8a)

![Screenshot_20240107_094921_AAAD](https://github.com/shmykelsa/AAAD/assets/65751632/fbabfa1f-ee4d-4010-95a1-fae5c8a5b7fe)

**Comment by shmykelsa** [comment]
Contact support through the app:

Top right menu > Help > Yes
