### ISSUE TITLE
Provata ma qualcosa non funziona....

### ISSUE THREAD

**Issue by Prefaberg** [shmykelsa/AAAD#32]
Installata su un Poco F3 e scaricato AAMIRROR, collegata tramite Android auto ad una Renault Clio V......la lista delle applicazioni viene mostrata ma qualsiasi applicazione si va ad aprire non fa altro che oscurare lo schermo del sistema auto.....l'audio arriva ma nessuna immagine, anzi sparisce tutto e non c'è modo di tornare alla normalità se  non uscendo da Android auto.....

**Comment by Ivano240161** [comment]
Ciao , stesso problema anche io , installata su Galaxy S9plus...collegato alla mia Ford Fiesta Ecoboost...lista delle applicazioni visibile ma cliccando su qualsiasi app questa si apre sul telefonino ma lo schermo rimane scuro e non mi sembra nemmeno di sentire alcun suono a differenza di te. Speriamo ci diano una soluzione al problema altrimenti così non serve a nulla...

**Comment by dpeddi** [comment]
- Xiaomi mi 10t pro (android 10)
- peugeot con NAC wave3

Ho provato screen2auto, aa mirror, aastream e aa mirror plus...
Più o meno con tutti ho avuto lo stesso problema da voi segnalato... nel senso che a volte funziona

AA MIRROR: Vecchiotto... meglio lasciare stare
AA MIRROR PLUS: quando funziona, non cattura il touch
SCREEN2AUTO: quando funziona, funziona bene (incluso touch, escluso ovviamente i video da programmi che utilizzano il DRM tipo timvision, netflix, chili, disney)...

Da quanto ho visto sembra sia molto importante verificare che :
- "Modificare le impostazioni di sistema" che corrisponde alla possibilità di effettuare la cattura schermo sia abilitato per il programma installato

Su xiaomi inoltre sembra necessario impostare per il programma installato
- "Risparmio energetico" su Nessuna restrizione
- "Avvio automatico": si

Ciò nonostante non sempre mi sta funzionando la cattura schermo. 
Non credo sia un problema di AAAD, ma magari lo sviluppatore saprà darci una dritta :-)...

grazie

**Comment by danis69** [comment]
Anche io ho lo stesso problema. Ho installato screen2auto da AAAD, e il tablet dell'auto lo vede, ma quando faccio tap su una delle app del tablet auto, lo schermo diventa nero e l'app viene aperta solo sullo smartphone (POCO M3). Voi avete risolto?

**Comment by danis69** [comment]
> Installata su un Poco F3 e scaricato AAMIRROR, collegata tramite Android auto ad una Renault Clio V......la lista delle applicazioni viene mostrata ma qualsiasi applicazione si va ad aprire non fa altro che oscurare lo schermo del sistema auto.....l'audio arriva ma nessuna immagine, anzi sparisce tutto e non c'è modo di tornare alla normalità se non uscendo da Android auto.....

ho lo stesso problema. tu hai risolto?

**Comment by danis69** [comment]
> Ciao , stesso problema anche io , installata su Galaxy S9plus...collegato alla mia Ford Fiesta Ecoboost...lista delle applicazioni visibile ma cliccando su qualsiasi app questa si apre sul telefonino ma lo schermo rimane scuro e non mi sembra nemmeno di sentire alcun suono a differenza di te. Speriamo ci diano una soluzione al problema altrimenti così non serve a nulla...

Ciao, ho lo stesso problema. tu hai risolto?

**Comment by Ivano240161** [comment]
> > Ciao , stesso problema anche io , installata su Galaxy S9plus...collegato alla mia Ford Fiesta Ecoboost...lista delle applicazioni visibile ma cliccando su qualsiasi app questa si apre sul telefonino ma lo schermo rimane scuro e non mi sembra nemmeno di sentire alcun suono a differenza di te. Speriamo ci diano una soluzione al problema altrimenti così non serve a nulla...
> 
> Ciao, ho lo stesso problema. tu hai risolto?

Finora no,speravo in un aiuto dello sviluppatore ma a quanto pare non legge i commenti...

**Comment by Prefaberg** [comment]
Ciao ragazzi....ho scritto al programmatore direttamente dall'app nella sezione help e la risposta è stata questa: "Ciao, 

come scritto chiaramente nelle condizioni d'uso e nelle FAQ, i problemi relativi alle app devono essere risolti con i programmatori delle app stesse. I software sono forniti così come sono. AAAD ha esclusivamente la responsabilità di farli vedere correttamente su Android Auto

Saluti
Gabriele Rizzo (aka Shmykelsa)".
Perciò mettiamoci l'animo in pace e speriamo nei futuri aggiornamenti delle varie applicazioni......😂😭...... considerando che alcune non hanno aggiornamenti da tempo presumo che non cambierà nulla in futuro.

**Comment by shmykelsa** [comment]
Not related to AAAD

**Comment by Prefaberg** [comment]
Prova ad attivare le impostazioni sviluppatore in android auto e lì
attivare origini sconosciute....

Il mar 6 giu 2023, 10:11 Duncan-Mac-Leod ***@***.***> ha
scritto:

**Comment by Duncan-Mac-Leod** [comment]
Su Android Auto dello smartphone l'ho già fatto, se invece intendi in quello dell'auto non so come si faccia

**Comment by Prefaberg** [comment]
Si, intendevo sullo smartphone l'intervento sulle impostazioni di Android
auto perché quello nel sistema dell'auto è solo un ricevitore.
Se hai Telegram prova ad unirti al gruppo "Android auto Italia", lì puoi
chiedere aiuto, c'è sempre qualcuno che sa dare i giusti suggerimenti.


Il mer 7 giu 2023, 14:32 Duncan-Mac-Leod ***@***.***> ha
scritto:
