### ISSUE TITLE
Wasted mothly download

### ISSUE THREAD

**Issue by julimonsa0x** [shmykelsa/AAAD#33]
Basically the title, I was downloading fermata, meantime put the AAAD app in multitask, when i came back there was no app downloaded and installer didn't come up.... I'm gonna have to pay it

**Comment by mikitcr** [comment]
+1

**Comment by McWild** [comment]
+1

**Comment by shmykelsa** [comment]
Hello, please proceed as follows:

- Open AAAD
- Open top right menu
- Select “about”
- Scroll down the text to the very bottom, the text might be cut!
- Make a screenshot
- Send the screenshot to help.aaad@gmail.com with subject of the mail “PRO VALIDATE ME”
