### ISSUE TITLE
does not work with Oppo reno 2 android 10

### ISSUE THREAD

**Issue by salvo1995** [shmykelsa/AAAD#34]
Ho eseguito tutta la procedura di installazione, ma non visualizzo le applicazioni su Android auto.

**Comment by tesckio** [comment]
Anche a me, Oppo Reno 2z

**Comment by bovirus** [comment]
This is an English forum.
Please use English language.

**Comment by salvo1995** [comment]
I went through the entire installation procedure, but I don't see the applications on Android auto. Oppo reno 2 not found

**Comment by Gaetano286** [comment]
Ho problemi con oppo Reno 2 mi potete aiutare

**Comment by bovirus** [comment]
@Gaetano286 

**Please use English**

**Comment by shmykelsa** [comment]
Duplicate of #27
