### ISSUE TITLE
perde audio su auto dopo telefonata

### ISSUE THREAD

**Issue by bygon69** [shmykelsa/AAAD#36]

**Comment by bygon69** [comment]
Funziona tutto correttamente fino alla ricezione di una chiamata poi dopo avere riagganciato l'audio passa al telefono e non più alla macchina. Per ripristinare devo staccare il telefono e rifare partire android auto. auto Peugeot 2008 2020

**Comment by shmykelsa** [comment]
Salve, questo non è un problema di AAAD. Si prega di contattare il produttore del telefono.
