### ISSUE TITLE
Stucked on loading

### ISSUE THREAD

**Issue by Alin2101** [shmykelsa/AAAD#37]
Android 11
Samsung s21 ultra
1.2 and 1.1 run ok, however when trying to download the actual apps it gets stucked on loading and then the app crushes.

**Comment by BigSilver657** [comment]
I'm Having the same problem with the S20 ultra, have you had any joy with this yet??..

**Comment by shmykelsa** [comment]
Hi,

long downloads, in this version of AAAD, may require long and the phone might say that the app is not responding. In that case, please, don't kill the app.

**Comment by BigSilver657** [comment]
![Screenshot_20210505-182950_AAAD](https://user-images.githubusercontent.com/83723187/117189626-52482b00-add6-11eb-99f2-7c221e21af61.jpg)
It gets to this point, so I select wait, its the only app running and I kept my screen on. I cancelled after 20mins, still no joy.. 😔

**Comment by Alin2101** [comment]
Hi, yes, I've got the pro version and is downloading everything, no issues. 

Sent from Yahoo Mail on Android 
 
  On Wed, May 5, 2021 at 21:17, ***@***.***> wrote:   



It gets to this point, so I select wait, its the only app running and I kept my screen on. I cancelled after 20mins, still no joy.. 😔

**Comment by BigSilver657** [comment]
All good now. Purchased the Pro version and now it works a treat! Thanks for your work Shmykelsa 👍👍
