### ISSUE TITLE
On Oppo reno 2z does't work

### ISSUE THREAD

**Issue by tesckio** [shmykelsa/AAAD#38]
I purchased the pro version but unfortunately connecting the smartphone to the car does not see any of the downloaded apps, I hope it resolves.
Oppo reno 2z android 10 on SYNK3 Ford Focus.

**Comment by bovirus** [comment]
@teschio

This is an English forum.
Please use English language.

Please avoid to open more than one ticket for same problem.

https://github.com/shmykelsa/AAAD/issues/34

Please provide max level of details about your system.

**Comment by tesckio** [comment]
Ok, I translated into English.

**Comment by shmykelsa** [comment]
Duplicate of #27

**Comment by tesckio** [comment]
Why close?
