### ISSUE TITLE
Google Assistant no longer working

### ISSUE THREAD

**Issue by soNburst** [shmykelsa/AAAD#40]
This app will be awesome if it can correct this gigantic issue. Google voice assistant no longer functions. It just says something went wrong. Installed only carstream 2.0.5. 

Samsung Note 20 Ultra

**Comment by shmykelsa** [comment]
Hi, 

I'm sorry but AAAD does not interfere in any way with Google Assistant. You may want to contact Samsung or Google for that.

**Comment by soNburst** [comment]
Maybe this was a coincidence that google assistant stopped working at the same time... I tried uninstalling carstream and aaad and google assistant still wouldn't connect. I then reinstalled aaad and i can no longer reinstall carstream. Is this how the 1 download is supposed to function? Thanks for the quick response.
