### ISSUE TITLE
Language  info

### ISSUE THREAD

**Issue by bovirus** [shmykelsa/AAAD#42]
@shmykelsa 

What language are included?
Please provide this info in README.md.

**Comment by shmykelsa** [comment]
Hi,

I should put a Crowdin badge, language included can be retrieved from Crowdin: https://crowdin.com/project/aaad

**Comment by bovirus** [comment]
@shmykelsa 

Thanks.

Please include this info in README.md.

**Comment by shmykelsa** [comment]
See https://github.com/shmykelsa/AAAD/commit/02dbd6123423ef8b9873823a40f42ab6fcfcc6a9

**Comment by bovirus** [comment]
@shmykelsa 

If yoyu can I would change something in the text

If you can sue multiline with CR/LF
Not use infinite
use teh same word (es. se vuoi)

ex.

Benvenuto su Android Auto Apps Downloader (AAAD). Questa utility aiuterà ad installare applicazioni personalizzate su Android Auto per telefoni non rootati. Selezionare l'applicazione che si desidera installare e attendere che il programma di installazione si presenti. Le descrizioni delle app sono disponibili sulla pressione prolungata.

Benvenuto **_in_** Android Auto Apps Downloader (AAAD). 
Questa utility **_ti_** aiuterà ad installare applicazioni personalizzate **_in_** Android Auto per telefoni non rootati. 
Seleziona l'applicazione che vuoi  installare e attendere che il programma di installazione si presenti. 
Le descrizioni delle app sono disponibili **_con una_** pressione prolungata.

Bene, ora aprire il dispositivo dal quale si desidera trasferire la licenza e selezionare "Voglio trasferire la licenza da qui", quindi scansiona questo codice QR

Bene, ora **_apri_** il dispositivo dal quale **_vuoi_** trasferire la licenza e **_seleziona_** "**_Trasferisci_** la licenza da qui", quindi scansiona questo codice QR

May I edit the file on Crowdin?
