### ISSUE TITLE
Not able to reinstall app

### ISSUE THREAD

**Issue by soNburst** [shmykelsa/AAAD#43]
Is it not possible to reinstall the same app that was chosen for the month? I uninstalled the app along with aaad trying to troubleshoot an issue I was having and can no longer install the same app. Is this how aaad was intentionally made? Thanks for aaad though. Great concept.

**Comment by McWild** [comment]
Have the same problem to.
Is it possible to reinstall the app that was installed before?

**Comment by shmykelsa** [comment]
> Is it not possible to reinstall the same app that was chosen for the month? I uninstalled the app along with aaad trying to troubleshoot an issue I was having and can no longer install the same app. Is this how aaad was intentionally made? Thanks for aaad though. Great concept.

I'm sorry but that's not possible. A download is counted when a download is made. AAAD has no responsibility if you decide to uninstall an app afterward
