### ISSUE TITLE
Performance Monitor

### ISSUE THREAD

**Issue by Reghion** [shmykelsa/AAAD#45]
Buonasera a tutti, 
possiedo un Poco F2 Pro con Android 11, auto Skoda Karoq My 2019, ho installato AAAD e sono riuscito a scaricare Carstream (funziona perfettamente), sempre gratuitamente ho installato Performance monitor, riesco a settare le impostazioni e lo vedo sul display dell'auto, purtroppo però i parametri impostati sugli indicatori rimangono a zero non avanzano ad esempio accelerando, le lancette non funzionano, potrebbe essere che non ho nessuna presa OBDI? ho seguito un tutorial x il settaggio dell'app, non capisco. 
Potreste cortesemente darmi una mano?
grazie,
saluti,
Massimo

**Comment by shmykelsa** [comment]
Duplicate of #9
