### ISSUE TITLE
Not working with Android Auto 6.4

### ISSUE THREAD

**Issue by mbushnaq00** [shmykelsa/AAAD#47]
After the update, I have lost all access to my apps downloaded from AAAD in Android Auto. Reinstalling the apps does not fix the issue.

FYI, AAAD version 1.3 is installed and I am using it on Galaxy S21 Ultra (Android 11)

**Comment by shmykelsa** [comment]
Please refer to this announcement https://t.me/AAADupdates/21

**Comment by shmykelsa** [comment]
Moving issue to #64
