### ISSUE TITLE
Touchscreen not working on the headunit

### ISSUE THREAD

**Issue by robi10101298** [shmykelsa/AAAD#5]
Samsung Note 10 lite, Ford Sync 3.4, the touchscreen it's not working on the head unit, and I've tried AAMirror and Screen2Auto. I think this is because of Samsung Kernel not allowing to be set to permissive, but this is a root related problem, I had this problem on an S20+ device.

**Comment by shmykelsa** [comment]
Hi, 

as clearly stated in the FAQ, any software inside AAAD is provided "as is" and the only responsibility of AAAD is to show the apps in Android Auto.

Please seek help from developer of the apps.
