### ISSUE TITLE
AaaD 1.3.1 on Realme x2 pro BUG

### ISSUE THREAD

**Issue by Michelemi** [shmykelsa/AAAD#56]
Ok i just tried the last 1.3.1 and 1.4 on my Realme x2pro but with : 
Android Auto 6.0 & 6.1 you will NOT get the apps you added to aper in Android Auto.

With Android Auto 6.2 & 6.3 & 6.4  and the new  AAAD 1.3.1 and 1.4.
You DO get the apps you added to Android Auto, BUT they all do not work. When you tap on them in Android Auto you always get a message saying:
" No new message during this drive"

This is the same message you get  when using apps like Whatsapp in Android Auto and there is no new message .

(FYI..My Realme x2 pro has Android 10 installed)
![16204599462386315437684648628135](https://user-images.githubusercontent.com/83631193/117531353-682a3b80-afe2-11eb-9109-42d614b5ae17.jpg)

**Comment by Altross** [comment]
I have the same phone with Android 10, Android Auto 6.3.6 and AAAD 1.4 PRO and still can't see the apps in my car.

I've tried to uninstall and reinstall AA, AAAD, and Fermata but it doesn't work.

**Comment by Firstcloned** [comment]
Hi same trouble with my Xiaomi redmi note 8 pro

**Comment by raylove718** [comment]
Same thing i pay for it  now nothing work

**Comment by raylove718** [comment]
On mirrorlink i put on netflix i get a green screen i get sound but that it help

**Comment by shmykelsa** [comment]
See [instructions](https://github.com/shmykelsa/AAAD/wiki/Fix-for-OnePlus-Realme-Oppo) for the fix
