### ISSUE TITLE
Crash install Screen2Auto

### ISSUE THREAD

**Issue by rengar-zz** [shmykelsa/AAAD#6]
I'm PRO.

Crash app when I try install Screen2Auto.

**Comment by shmykelsa** [comment]
Hi,

I'm aware of this problem and currently solving this. Please stay updated at t.me/AAADupdates

**Comment by shmykelsa** [comment]
Hi,

please try version 1.1

https://github.com/shmykelsa/AAAD/releases/tag/v1.1

**Comment by rengar-zz** [comment]
It's working.
