### ISSUE TITLE
Issues Samsung A71

### ISSUE THREAD

**Issue by zednanreh69** [shmykelsa/AAAD#64]
Pay for AAAD PRO, but not working in Samsung A71, i have android 11 and android auto versión 6.4.6.11714-release.

![Screenshot_20210511-142359_Android Auto](https://user-images.githubusercontent.com/62857517/117876579-24953300-b269-11eb-8a4a-519ffc1c031d.jpg)

**Comment by shmykelsa** [comment]
Moving issue to #60
