### ISSUE TITLE
touch screen not work on aa miror apk

### ISSUE THREAD

**Issue by sjele1** [shmykelsa/AAAD#66]
my touch screen in the car doesn't work on ll mirror apps. i have to move everything by touching the screen on my mobile phone! on fermata auto and carstream apk we get a touch on the car screen. fermata auto play two video and blocked . in carstream not work internal storage ! what should I do ?thank you

**Comment by shmykelsa** [comment]
Not related to AAAD.

Please seek help here: https://github.com/slashmax/AAMirror
