### ISSUE TITLE
Payment made but still says no download remaining

### ISSUE THREAD

**Issue by stevenbedekar** [shmykelsa/AAAD#71]
I've made payment of €3.5 but it still says you have no download remaining.

**Comment by shmykelsa** [comment]
This is not the right way to seek assistance for PRO version status. 

Please refer to the FAQs: https://github.com/shmykelsa/AAAD#how-long-will-my-pro-license-last

**Comment by stevenbedekar** [comment]
I've not wiped my mobile or did not do anything other than making payment. I'll mail the screenshot for reference on the mentioned e-mail id.
