### ISSUE TITLE
NUOVA VERSIONE aNDROID aUTO

### ISSUE THREAD

**Issue by gipa77** [shmykelsa/AAAD#77]
BUONA SERA A TUTTI SI POTREBBE SAPERE SE STATE FACENDO QUALCHE AGGIORNAMENTO PER FAR FUNZIONARE 
CARSTREAM
FERMATA AUTO

GRAZIE PERCOLLABORAZIONE
CORDALI SALUTI

**Comment by BoroB5** [comment]
Android se actualiza automáticamente a la versión 6.4.611713 y ya no funciona la aplicacion AAAd.
Que no cunda el PANICO.
Primero hay que entrar en los ajustes de Google Play y desactivar actualizaciones automáticas, lo malo será que debereis entrar de vez en cuando y actualizar manualmente las demas.
Desinstalar Android Auto, y yo lo he hecho desde esta pagina:
https://android-auto.uptodown.com/android/versions
instalais la ultima que funcionaba que es esta:
Android Auto
6.3.611323-release, y Voila, otra vez como antes

**Comment by zanlor** [comment]
Salve, purtroppo sul mio smartphone Samsung A50 non posso disinstallare Android Auto... e quindi non posso dare il downgrade. L'app AAAD non funziona più....
