### ISSUE TITLE
Screen2auto doesn't show up on AA

### ISSUE THREAD

**Issue by cayatecayote** [shmykelsa/AAAD#78]
I installed version 1.4 of AAAD, I installed screen2auto version 3.5.2 beta, I gave it all the permissions (including root although I don't have root, otherwise it wouldn't let me continue), I looked at AA and it didn't appear, then I downgraded S2A to version 3.4.6 in case that was the reason, but it still did not work, then I came to this page of issues and saw that the problem was the AA version, I downgraded it to 6.3 and now I see the Carstream app (which had been installed by another app) but I still don't see sceen2auto.
What could be the problem??

**Comment by raylove718** [comment]
I pay for a apk that doesn't work than i try aa tweaker  that didn't help cause u need root access

**Comment by raylove718** [comment]
Go to download android auto 6.3 and it work i just did it

**Comment by shmykelsa** [comment]
This is an English website, please speak in english.

**Comment by cayatecayote** [comment]
Sorry, I saw a lot of issues in spanish that's why I reported this one in spanish too.
Now it's in english.

**Comment by Joe10s** [comment]
Had the same problem. Downgrades to AA 6.3...

This helped.

https://youtu.be/3U112pZz6Dw

**Comment by raylove718** [comment]
I need help why on netflix i get a green screen please help

**Comment by shmykelsa** [comment]
> I installed version 1.4 of AAAD, I installed screen2auto version 3.5.2 beta, I gave it all the permissions (including root although I don't have root, otherwise it wouldn't let me continue), I looked at AA and it didn't appear, then I downgraded S2A to version 3.4.6 in case that was the reason, but it still did not work, then I came to this page of issues and saw that the problem was the AA version, I downgraded it to 6.3 and now I see the Carstream app (which had been installed by another app) but I still don't see sceen2auto.
> What could be the problem??

Please make sure that during installation AAAD is selected as method to install Screen2Auto. Upon version selection you should have a prompt asking you if you want to open with package installer or AAAD. If the prompt does not come out, please change browser.

**Comment by salman-mukhtar** [comment]
> I need help why on netflix i get a green screen please help screen 2 auto or any mirrorlink app

I have the same issue. When i run netflix, android auto shows nothing on the screen except sub titles.
The actual movie runs on the phone.

**Comment by Denusdv** [comment]
seems like Google made the AA update policy, from now you can't start the older versions.
any ideas for a workaround?
