### ISSUE TITLE
AAAD 1.01

### ISSUE THREAD

**Issue by Salvertor** [shmykelsa/AAAD#8]
He comprado la versión pro y no puedo actualizar a 1.01

**Comment by remium796** [comment]
Can I pay for the pro version of the program via Webmoney.

**Comment by shmykelsa** [comment]
No

**Comment by Salvertor** [comment]
> He comprado la versión pro y no puedo actualizar a 1.01

Ya esta actualizado, ya era hora que alguien sacara una apk como esta, funciona casi perfectamente, en samsung s 20 con android 11: 
carstream,aamirror y aamirror plus perfecto
fermata auto no se puede instalar
