### ISSUE TITLE
kia sportage 2020

### ISSUE THREAD

**Issue by rampas78** [shmykelsa/AAAD#80]
Buongiorno,
ho provato sul mio android auto, KIA SPORTAGE 2020 ogni volta che avvio un app mi dice "non ci sono messaggi da visionare" e non si avvia nulla, ne car stream , aa mirror, o altro.
Ho ovviamente comprato la versione pro ma comunque al momento non funziona, non visualizza.
Versione android auto installata sul mio a72 OPPO è la  6.3.611324
E' possibile creare tipo una lista di auto o almeno marche dove l'attuale app funziona?

Chiaro che son ben contento di aver contribuito e spero in aggiornamenti continui per arrivare al funzionamento anche sulla mia auto.
Grazie

**Comment by quartodemone** [comment]
Su Oppo al momento non funziona, attendiamo aggiornamento

**Comment by Mello83** [comment]
Ciao anche io ho lo stesso identico problema😔
Ho un oppo a52 con Android 10. ho fatto il downgrade di Android auto alla 6.3... Ma qualunque app che apro mi appare il messaggio identico al tuo... Su mokka
Speriamo gli sviluppatori ci aiutino... Anche io ho la versione PRO...
