### ISSUE TITLE
I can't see Netflix or Disney+ or LocalTV Streaming (Movistar)

### ISSUE THREAD

**Issue by esnover70** [shmykelsa/AAAD#82]
Can't watch other streaming services like netflix or local streaming apps. I only see a black screen.

On the other hand, that it can be used with the most current versions of Android Auto.

**Comment by shmykelsa** [comment]
Not related to AAAD

https://github.com/shmykelsa/AAAD#i-have-a-problem-with-an-app-installed-by-aaad-could-you-help-me-out
