### ISSUE TITLE
Performance Monitor & Citroen C3

### ISSUE THREAD

**Issue by Ren-costa** [shmykelsa/AAAD#84]
Buongiorno a tutti, ho installato Performance Monitor su Redmi Note 8 Pro per utilizzo su Citroen C3. Il programma si avvia regolarmente su Android Auto (vers. 6.4.611714: ho impostato i parametri da mostrare sui vari indicatori (pressione degli singoli pneumatici, voltaggio batteria, ecc.) e i settaggi relativi a tema, font e sfondo: però gli indicatori dei vari parametri rimangono sullo zero, tranne all'avvio della app, quando si spostano tutti sul max per tornare subito sullo zero. Nelle impostazioni sul telefono ho messo "Nessuna restrizione" su risparmio energetico e ho attivato "Avvio automatico": cosa sto sbagliando? Grazie a tutti!

**Comment by quartodemone** [comment]
Funziona solo nelle auto del gruppo Vag

**Comment by Ren-costa** [comment]
Grazie per la risposta. Certo che sarebbe stato utile precisarlo al momento del download: al contrario, specificando che per utilizzo su auto del Gruppo VAG era necessario scaricare anche un'estensione apposita, si lasciava intendere che può essere utilizzato su tutte le auto ...

**Comment by shmykelsa** [comment]
Not related to AAAD
