### ISSUE TITLE
Does not work with Android Auto v6.4.611714

### ISSUE THREAD

**Issue by charlieporth1** [shmykelsa/AAAD#87]
Does not work with Android Auto v6.4.611714. I've got a galaxy S10 running OneUI 3.1 and the latest version of AA seems to break AAAD
Interestingly Android Auto seems to pick up the packages it just doesn't seem to be displaying them on the car. 

![Screenshot_20210608-180839_Android Auto.jpg](https://user-images.githubusercontent.com/13573364/121268970-940c3b80-c884-11eb-8b91-5de6d3127bc8.jpg)

![Screenshot_20210608-180759_Android Auto.jpg](https://user-images.githubusercontent.com/13573364/121268926-7e971180-c884-11eb-8cd1-38b4121823e7.jpg)

**Comment by BoroB5** [comment]
Android se actualiza automáticamente a la versión 6.4.611713 y ya no funciona la aplicacion AAAd.
Que no cunda el PANICO.
Primero hay que entrar en los ajustes de Google Play y desactivar actualizaciones automáticas, lo malo será que debereis entrar de vez en cuando y actualizar manualmente las demas.
Desinstalar Android Auto, y yo lo he hecho desde esta pagina:
https://android-auto.uptodown.com/android/versions
instalais la ultima que funcionaba que es esta:
Android Auto
6.3.611323-release, y Voila, otra vez como antes
