### ISSUE TITLE
License PRO

### ISSUE THREAD

**Issue by EdjOne** [shmykelsa/AAAD#89]
Hi cool developers. 

Have an issue, jut pai for PRO, but licence not implemented, money was taken by pay pal.Any idea how to solve?

Andrew

**Comment by shmykelsa** [comment]
For any issue regarding license, please refer to the FAQs and avoid opening issues:

https://github.com/shmykelsa/AAAD#how-long-will-my-pro-license-last

**Comment by EdjOne** [comment]
Hi, what to put in to subject in my case?

**Comment by shmykelsa** [comment]
> Hi, what to put in to subject in my case?

PROWIPED will do.
