### ISSUE TITLE
Performance monitor 

### ISSUE THREAD

**Issue by Zaraki887** [shmykelsa/AAAD#9]
Sto avendo problemi con questa di app e basta in quanto le altre funzionano tutte ! In pratica si installa ma non visualizza nulla fermo o va in crash oppure si chiude subito ,a parte una volta che spegnendo l'auto ho notato segnava la temperatura dell'acqua acceso il motore andava! Allora ho spento staccato il telefono è tornata a non funzionare. Adesso è disinstallata reinstallata e non la apre proprio più!

**Comment by shmykelsa** [comment]
Duplicato di #7

**Comment by Zaraki887** [comment]
Scusami se disturbo ancora ma il performance monitor non va prima si apriva
e craschava fino a quando poi rimaneva attiva ma non segnava nulla. Poi lo
lasciata attiva mentre andavo e nulla appena ho spento la macchina ha
segnato la temperatura ho acceso e andava. Spento riacceso e non funzionava
più . Disinstallare reinstallata  e non si apre proprio più è dovuto a
qualche bug dell' app o AAAD che istalla male per via dell'errore che
spunta subito?

Il sab 1 mag 2021, 17:21 Gabriele Rizzo ***@***.***> ha
scritto:
